Add vesting contracts as templates. Contracts credit to Alex
dltxio/solidity-template pull request #42
Opened 2022-02-11 05:27 UTC by OptimusOpus

Contracts credit to Alex aka xiangzhe0812

2022-03-31 23:11 UTC, bitcoinbrisbane commented on contracts/SaleVesting.sol
> +    address public immutable RITE;
Shouldnt be RITE

2022-03-31 23:11 UTC, bitcoinbrisbane commented on contracts/SaleVesting.sol
> +        RITE = _RITE;
And here.

2022-03-31 23:12 UTC, bitcoinbrisbane requested changes
Needs to have unit tests and more generic names.

2022-04-01 07:00 UTC, rellfy commented
SaleVesting and TeamVesting are pretty much the same contract. For the template we can add just one not to be redundant

2023-05-09 05:27 UTC, closed without merging