Create NFT template
dltxio/solidity-template pull request #51
Opened 2022-04-20 05:31 UTC by jrocca82

Creates ERC721 template with unit tests and deploy script

2022-04-20 06:15 UTC, OptimusOpus approved these changes
LGTM, keeping in mind I have only played with ERC721s in my own personal projects, so not sure if there are standards I am unaware of here

2022-04-20 23:41 UTC, rellfy requested changes
Might need a few more unit tests to increase the coverage to at least 90%

2022-04-20 23:41 UTC, rellfy commented on contracts/NFT.sol
> +        0x1156B992b1117a1824272e31797A2b88f8a7c729;
Please make this a constructor argument instead of a constant. It should be `immutable` then. It makes more sense that way for templates.

2022-04-20 23:41 UTC, rellfy commented on .env.development
> +CONSTRUCTOR_TOKEN_MAX=100
I believe this should be `CONSTRUCTOR_NFT_MAX` as used in the deployment script

```suggestion
CONSTRUCTOR_NFT_MAX=100
```

2022-04-20 23:41 UTC, rellfy commented on contracts/NFT.sol
> +    }
We should emit an event when the base uri changes, with the new baseURI as argument. Also, shouldn't the constructor have an initial baseURI argument?

2022-04-20 23:41 UTC, rellfy commented on contracts/NFT.sol
> +    }
```suggestion
    function toggleSaleStatus() external onlyOwner {
        isSaleActive = !isSaleActive;
    }
```
Should emit an event here

2022-04-20 23:41 UTC, rellfy commented on contracts/NFT.sol
> +    }
This function name can be misleading. It modifies the variable, so it is not a `view` function. Pleasere name it to something like `increaseTokenId`

2022-04-21 02:23 UTC, rellfy requested changes
Looks good, just some more small changes

2022-04-21 02:23 UTC, rellfy commented on .env.development
> +CONSTRUCTOR_BASE_URI="https://tokentokens.com"
Should start with `CONSTRUCTOR_NFT`

2022-04-21 02:23 UTC, rellfy commented on contracts/NFT.sol
> +    bool public isSaleActive;
```suggestion
    /** @dev This contract's address. */
    address private immutable _self;
    /** @dev The base NFT URI. *'/
    string private baseURI;
    /** @dev This address is used for if current owner want to renounceOwnership. */
    address private immutable fixedOwnerAddress;
    /** @dev Counter to keep track of tokens minted. */
    Counters.Counter private tokenCounter;
    
    /** @dev The maximum supply of tokens. */
    uint16 public immutable maxTokens;
    bool public isMintEnabled;
```
I've just reordered private/public, added comments. and renamed sale to mint.

2022-04-21 02:23 UTC, rellfy commented on contracts/NFT.sol
> +    event SaleStatusChanged(bool updatedSaleStatus);
```suggestion
    event MintStatusChanged(bool updatedMintStatus);
```

2022-04-21 02:23 UTC, rellfy commented on contracts/NFT.sol
> +    }
```suggestion
    modifier mintEnabled() {
        require(isMintEnabled, "Mint is not enabled");
        _;
    }
```

2022-04-21 02:23 UTC, rellfy commented on contracts/NFT.sol
> +    }
```suggestion
    function toggleMintStatus() external onlyOwner {
        isMintEnabled = !isMintEnabled;
        emit MintStatusChanged(isMintEnabled);
    }
```

2022-04-21 02:23 UTC, rellfy commented on contracts/NFT.sol
> +        saleActive
```suggestion
        mintEnabled
```

2022-04-21 03:52 UTC, rellfy approved these changes

2022-04-21 04:53 UTC, merged